additionalProperties:
  key: mytesla-selfhost-traefik
  name: Mytesla Self Host (Traefik)
  tags:
    - Tool
  description:
    en: A self-hosted data logger for Tesla vehicles with Traefik HTTPS (Let's Encrypt)
    zh: 特斯拉车辆数据记录器（Traefik HTTPS 版）
    zh-Hant: 特斯拉車輛數據記錄器（Traefik HTTPS 版）
  type: tool
  crossVersionUpdate: false
  limit: 0
  website: https://mytesla.cc/
  document: https://manual.mytesla.cc/
